In [1]:
import logging
import os
import sys
import papermill as pm

notebook_dir = os.getcwd()
project_dir = os.path.dirname(notebook_dir)

if project_dir not in sys.path:
    sys.path.insert(0, project_dir)

print(f'Notebook dir: {notebook_dir}\nProject dir: {project_dir}.')

from collections import namedtuple
import numpy as np

logging.getLogger().setLevel(logging.INFO)
%load_ext autoreload
%autoreload 2

Notebook dir: /Users/farahbaracat/Documents/PhD Research/Code/class_eng_snn/notebooks
Project dir: /Users/farahbaracat/Documents/PhD Research/Code/class_eng_snn.


In [2]:
NOTEBOOK_DIR = os.path.join(notebook_dir, "generated_notebooks")

if not os.path.exists(NOTEBOOK_DIR):
    os.makedirs(NOTEBOOK_DIR)

# Run with multiple random seeds on all days

In [3]:
# generate 20 random integers
np.random.seed(42)  # fix seed for random number generator, to reproduce the same results
N = 10
seeds = np.random.randint(0,1000, N)
seeds
# seeds[2:]

array([102, 435, 860, 270, 106,  71, 700,  20, 614, 121])

In [4]:
seeds[5:]

array([ 71, 700,  20, 614, 121])

In [5]:
parameters = dict(
    day = 16,
    session = '01',
    feature = 'power', 
    wind_size = 0.100,  
    overlap_perc = 0.5,
    organize_strat = 'flx_vs_ext_separate',
    seed = 10,
    k_cv=5
)


for day in [23]: #[16,17,23]
    for seed in seeds[5:]:
 
        print(f"Day {day} | Session {parameters['session']}  |  Seed {seed}")
        parameters['day'] = day
        parameters['seed'] = int(seed)
        parameters['session'] = '01'
        output_notebook_name = f"svm_day{day}_seed{seed}_session_{parameters['session']}.ipynb"
        pm.execute_notebook(
            '1.svm_per_day.ipynb',
            os.path.join(NOTEBOOK_DIR, output_notebook_name),
            parameters=parameters
        )

Day 23 | Session 01  |  Seed 71


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 23 | Session 01  |  Seed 700


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 23 | Session 01  |  Seed 20


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 23 | Session 01  |  Seed 614


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


# Sweep window sizes with fixed overlap

In [31]:
wind_sizes= np.concatenate([np.arange(0.02,0.2,0.02), np.arange(0.2, 0.99,0.05)])#np.linspace(0.02,0.95,16)
wind_sizes, len(wind_sizes)

(array([0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 , 0.25,
        0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 ,
        0.85, 0.9 , 0.95]),
 25)

In [33]:
parameters = dict(
    day = 16,
    session = '01',
    feature = 'power', 
    wind_size = 0.100,  
    overlap_perc = 0.5,
    organize_strat = 'flx_vs_ext_separate',
    seed = 10,
    k_cv=5
)

for wind_size in wind_sizes:
    print(f"Day {parameters['day']} | Session {parameters['session']}  |  Wind_size {wind_size}")
    parameters['wind_size'] = wind_size
    output_notebook_name = f"svm_day{day}_seed{seed}_session_{parameters['session']}_windsize_{wind_size}.ipynb"
    pm.execute_notebook(
        '1.svm_per_day.ipynb',
        os.path.join(NOTEBOOK_DIR, output_notebook_name),
        parameters=parameters
    )

Day 16 | Session 01  |  Wind_size 0.02


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.04


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.06


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.08


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.1


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.12000000000000001


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.13999999999999999


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.16


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.18


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.2


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.25


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.3


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.35


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.39999999999999997


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.44999999999999996


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.49999999999999994


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.5499999999999999


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.5999999999999999


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.6499999999999999


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.7


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.7499999999999998


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.7999999999999998


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.8499999999999999


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.8999999999999999


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.


Day 16 | Session 01  |  Wind_size 0.9499999999999997


Executing:   0%|          | 0/20 [00:00<?, ?cell/s]

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
